/**
 * SPDX-License-Identifier: Apache-2.0
 */

import { MenuItem, Wine, Zone, Testimonial, Promotion } from './types';

export const WINES: Wine[] = [
  {
    id: 'w1',
    name: 'Château Margaux Grand Cru',
    vintage: '2018',
    type: 'Red',
    description: 'A classic blend of Cabernet Sauvignon, Merlot, and Cabernet Franc. Delicate violet aroma with hints of dark cherries, graphite, and velvet tannins.',
    intensity: 'Full-Bodied',
  },
  {
    id: 'w2',
    name: 'Domaine de la Romanée-Conti',
    vintage: '2019',
    type: 'Red',
    description: 'Extraordinarily complex Pinot Noir featuring wild strawberry notes, damp forest floor, exotic Asian spices, and an endlessly structured, silky mouthfeel.',
    intensity: 'Medium',
  },
  {
    id: 'w3',
    name: 'Cervaro della Sala Chardonnay',
    vintage: '2021',
    type: 'White',
    description: 'Bright straw-yellow with golden highlights. Notes of white flowers, sweet butter, toasted vanilla, and a beautifully crisp, mineral-driven acidity.',
    intensity: 'Medium',
  },
  {
    id: 'w4',
    name: 'Cloudy Bay Sauvignon Blanc',
    vintage: '2022',
    type: 'White',
    description: 'An explosive bouquet of ripe passionfruit, kaffir lime leaf, and ruby red grapefruit. Extremely crisp and vibrant with slate-like minerality.',
    intensity: 'Light',
  },
  {
    id: 'w5',
    name: 'Dom Pérignon Vintage Rosé',
    vintage: '2008',
    type: 'Sparkling',
    description: 'A masterpiece of balance. Bright Pinot Noir grip with wild red berries, candied citrus peel, toasted brioche, and fine, creamy persistent bead.',
    intensity: 'Medium',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'Mozzarella Al Forno',
    price: 1695,
    category: 'Starters',
    description: 'Crumb-coated golden mozzarella infused with jalapeño, Kalamata olives, and capers. Served over rich house tomato fondue & basil oil.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Vegetarian'],
    flavorProfile: 'Rich',
    recommendedWineId: 'w4',
  },
  {
    id: 'm2',
    name: 'Jumbo Prawn Tempura',
    price: 2295,
    category: 'Starters',
    description: 'Crispy wild-caught prawns wrapped in a light-as-air Japanese tempura batter, seasoned with sea salt. Served with a delicate ginger-soy dipping sauce.',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Nut-Free'],
    flavorProfile: 'Delicate',
    recommendedWineId: 'w3',
  },
  {
    id: 'm3',
    name: 'Grand Caesar Salad',
    price: 1795,
    category: 'Salads',
    description: 'Crisp hand-torn romaine hearts tossed in rich house Caesar dressing, capped with black olives, semi-dried heirloom tomatoes, toasted pain de mie croutons, and fine Parmigiano Reggiano shaving.',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Nut-Free'],
    flavorProfile: 'Rich',
    recommendedWineId: 'w4',
  },
  {
    id: 'm4',
    name: 'Ruby Citrus & Walnut Quinoa Salad',
    price: 1995,
    category: 'Salads',
    description: 'Vibrant white quinoa, baby spinach leaves, fresh grapefruits, and crisp apples tossed in raw local honey-vinaigrette, topped with raw walnuts and imported Greek feta.',
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Vegetarian'],
    flavorProfile: 'Delicate',
    recommendedWineId: 'w4',
  },
  {
    id: 't1',
    name: 'Chicken Karahi with Desi Ghee',
    price: 3595,
    category: 'Traditional',
    description: 'Free-range chicken slow-cooked in clean organic butter & pure Desi Ghee with sun-ripened tomatoes, crushed black peppercorns, julienned fresh ginger, and mountain green chilies in a cast-iron wok.',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Bold',
    recommendedWineId: 'w1',
  },
  {
    id: 't2',
    name: 'Mutton Karahi Royal',
    price: 5695,
    category: 'Traditional',
    description: 'Premium baby goat cuts slow-simmered in rich desi ghee with roasted hand-ground spices, coriander seeds, fresh tomato pulp, and whole charred chilies. Absolute classic.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Bold',
    recommendedWineId: 'w1',
  },
  {
    id: 't3',
    name: 'Bhuna Palak Gosht',
    price: 5795,
    category: 'Traditional',
    description: 'Tender prime mutton shank cooked meticulously with fresh organic baby spinach leaf purée, roasted garlic clovers, and rich house garam masala spices for an authentic royal flavor.',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Rich',
    recommendedWineId: 'w2',
  },
  {
    id: 's1',
    name: 'New York Strip Steak',
    price: 3695,
    category: 'Steaks',
    description: 'Premium 45-day dry-aged Angus striploin, flame-charred to medium-rare over oak wood, basted with farm garlic butter and organic herbs. Served with crisp hand-cut heirloom potato wedges.',
    image: 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free', 'Dairy-Free'],
    flavorProfile: 'Bold',
    recommendedWineId: 'w1',
  },
  {
    id: 's2',
    name: 'Mutton Aurangzebi Chops',
    price: 5995,
    category: 'Steaks',
    description: 'Double-cut premium mutton ribs marinated overnight in raw green papaya skins and Mughal-style spices, charred over smoking charcoal. Side of fingerling potatoes & robust mint chutney.',
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Bold',
    recommendedWineId: 'w2',
  },
  {
    id: 's3',
    name: 'Shiitake Butter Grilled Chicken',
    price: 2395,
    category: 'Steaks',
    description: 'Organic chicken breasts pan-basted with tarragon-infused butter and layered with rich cream of wild Shiitake mushroom sauce. Accompained by silk mash potato purée.',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Rich',
    recommendedWineId: 'w3',
  },
  {
    id: 'f1',
    name: 'Red Snapper with Lemon Butter',
    price: 3395,
    category: 'Seafood',
    description: 'Pan-seared deep-sea red snapper fillet with flaky texture, blanketed in a luxurious reduction of yellow lemon juice, dry chardonnay, and organic butter. Side of asparagus spears.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Delicate',
    recommendedWineId: 'w3',
  },
  {
    id: 'f2',
    name: 'Charcoal Tandoori Fish Tikka',
    price: 2995,
    category: 'Seafood',
    description: 'Cubed premium center-cut seabass fillet marinated in hand-ground red chilies, crushed cumin seeds, lemon zest, and rich yogurt, roasted over active coals. Tamarind chutney side.',
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Gluten-Free', 'Nut-Free'],
    flavorProfile: 'Spicy',
    recommendedWineId: 'w4',
  },
  {
    id: 'c1',
    name: 'Szechuan Chili Beef Dry',
    price: 2395,
    category: 'Chinese',
    description: 'Hand-sliced prime beef tenderloin strips crisp-fried and tossed in premium dark soy, whole red Szechuan peppercorns, roasted garlic slices, and toasted sesame oil for a tingling heat.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Dairy-Free', 'Nut-Free'],
    flavorProfile: 'Spicy',
    recommendedWineId: 'w2',
  },
  {
    id: 'c2',
    name: 'Sizzling Kung Pao Chicken',
    price: 1995,
    category: 'Chinese',
    description: 'Wok-seared marinated chicken breast dices tossed with scallions, scorched dry red chilies, green peppers, and a classic sweet-savory peppercorn sauce, finished with crispy peanuts.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Dairy-Free'],
    flavorProfile: 'Spicy',
    recommendedWineId: 'w4',
  },
  {
    id: 'd1',
    name: 'Molten Belgian Fudge Lava',
    price: 1595,
    category: 'Desserts',
    description: 'Intense single-origin Belgian dark chocolate cake with a self-saucing, warm molten lava center. Dust of gold leaf, paired with cream-laden Madagascar vanilla bean ice cream.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Vegetarian', 'Nut-Free'],
    flavorProfile: 'Sweet',
    recommendedWineId: 'w5',
  },
  {
    id: 'd2',
    name: 'Madison Avenue Raspberry Cheesecake',
    price: 1595,
    category: 'Desserts',
    description: 'Authentic dense and velvet New York style baked cheesecake layered over crunchy Lotus graham crust, dressed in fresh crimson raspberry compote and edible floral leaves.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Vegetarian'],
    flavorProfile: 'Sweet',
    recommendedWineId: 'w5',
  },
  {
    id: 'd3',
    name: 'Traditional Royal Gulab Jamun',
    price: 895,
    category: 'Desserts',
    description: 'Soft milk-solid dumplings cardamon-infused, deep-fried in organic clarified butter (ghee) and soaked in sweet syrup, served warm over a pool of saffron custard.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format,compress&fm=webp&fit=crop&q=60&w=600',
    dietary: ['Vegetarian'],
    flavorProfile: 'Sweet',
    recommendedWineId: 'w5',
  },
];

export const ZONES: Zone[] = [
  {
    id: 'zone-main',
    name: 'The Obsidian Grand Hall',
    description: 'The dramatic core of our restaurant. Hand-carved high mahogany arches, absolute obsidian granite table tables, custom leather booths, and massive crystal chandeliers emitting a soft, golden twilight glow.',
    capacityLimit: 80,
    extraCost: 0,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    features: ['Classic Ambiance', 'Soft Live Music Acoustic', 'Rich Acoustics', 'Spacious Seating'],
  },
  {
    id: 'zone-veranda',
    name: 'The Glasshouse Veranda',
    description: 'An ethereal glass dome structure decorated with overhanging jungle flora, ferns, and glowing lanterns. Unmatched, panoramic 180-degree glass views of the beautiful night lights of the city.',
    capacityLimit: 40,
    extraCost: 2000,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    features: ['180° City Skyline View', 'Candlelit Tables', 'Lush Tropical Plants', 'Starlit Ceiling'],
  },
  {
    id: 'zone-chef',
    name: 'The Exclusive Chef\'s Table',
    description: 'Limited to 10 guests per evening. A continuous, raw lava-stone u-shaped bar overlooking our active open-concept steel copper kitchen. Engage directly with Chef as she prepares custom tastings.',
    capacityLimit: 10,
    extraCost: 5000,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    features: ['Interaction with Executive Chef', 'Custom Pre-tasting Items', 'Open Kitchen Showcase', 'Curated Wine pairings'],
  },
];

export const PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    title: 'The Saffron Sunday Brunch',
    subtitle: 'A Royal Daytime Affair',
    description: 'Elevate your Sundays with an endless spread of over 60 traditional breakfast items, French patisserie, live pan-basted pancakes, and fresh local chaat stations, overlooking the fresh pine breeze.',
    price: 'Rs. 3,490 per person',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    tags: ['Live Stations', 'Sunday Exclusive', 'Patisserie Showcase'],
  },
  {
    id: 'promo-2',
    title: 'Executive Sommelier’s Masterclass',
    subtitle: 'Art of Elite Wine Pairing',
    description: 'A 5-course customized degustation menu where each course (scallops, duck breasts, to dry-aged steaks) is served with a curated glass of premium aged vintage wine, explained by our Head Sommelier.',
    price: 'Rs. 15,500 per person',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    tags: ['Aged Vintages', '5-Course Tastings', 'Limited Seating'],
  },
  {
    id: 'promo-3',
    title: 'The Bahar-e-Ramadan Intimate Feast',
    subtitle: 'Seasonal Holy Celebrations',
    description: 'Savor traditional hot dates, refreshing mint coolers, deep and rich Mughal paya, Lahori fried red snapper, and authentic dum clay biryani, finished with hot syrup-sweet Gulab Jamun.',
    price: 'Rs. 5,595 per person',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format,compress&fm=webp&fit=crop&q=60&w=800',
    tags: ['Clay Pot Slow Cooking', 'Ramadan Exclusive', 'Dates & Coolers'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Aqsa Gul',
    rating: 5,
    text: 'I had an absolutely marvelous experience dining at The Obsidian Dome! The food from presentation to taste was top-tier. The Veranda view of the Islamabad city line felt celestial. It is definitely a must-visit in Daman-e-Koh.',
    location: 'Islamabad, Pakistan',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format,compress&fm=webp&fit=crop&crop=faces&q=60&w=100',
  },
  {
    id: 't-2',
    name: 'Muhammad Ismail',
    rating: 5,
    text: 'Wonderful hospitality! The Mutton Karahi cooked in organic Desi Ghee was melt-in-the-mouth, and the sommelier wine recommendation (Château Margaux) was absolutely divine. The candlelit atmosphere next to the glass dome was cozy.',
    location: 'Karachi, Pakistan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format,compress&fm=webp&fit=crop&crop=faces&q=60&w=100',
  },
  {
    id: 't-3',
    name: 'Yasmine Evren',
    rating: 5,
    text: 'The exclusive Chef’s Table was an extraordinary sensory journey. Watching the culinary master craft the gold-capped molten Belgian fudge right in front of us while sharing historical inspirations was unforgettable.',
    location: 'London, UK',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format,compress&fm=webp&fit=crop&crop=faces&q=60&w=100',
  },
];